from typing import TypedDict
from typing import Any


class RoverState(TypedDict):

    # User's original question
    user_query: str

    # List of actions decided by the planner
    # Example:
    # [
    #   {"tool": "SEARCH_OBJECT", "object_name": "keyboard"},
    #   {"tool": "COUNT_OBJECT_OCCURRENCES", "object_name": "keyboard"}
    # ]
    actions: list

    # Results produced by every executed tool
    # Example:
    # [
    #   {"tool": "SEARCH_OBJECT", "result": [...]},
    #   {"tool": "COUNT_OBJECT_OCCURRENCES", "result": {"count": 6}}
    # ]
    tool_results: list[Any]

    # Final response generated by the LLM
    final_answer: str